import { useState } from 'react'
import { Mail, Copy, CheckCheck, Download, ExternalLink, Github } from 'lucide-react'

export default function EmailOutput({ email, portfolioLinks, providerUsed }) {
  const [copied, setCopied] = useState(false)

  if (!email) return null

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(email)
      setCopied(true)
      setTimeout(() => setCopied(false), 2200)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = email
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      setCopied(true)
      setTimeout(() => setCopied(false), 2200)
    }
  }

  function handleDownload() {
    const blob = new Blob([email], { type: 'text/plain' })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.download = 'job-application-email.txt'
    link.click()
    URL.revokeObjectURL(link.href)
  }

  return (
    <div className="card p-6 animate-slide-up">
      {/* Header row */}
      <div className="flex items-center justify-between mb-5 flex-wrap gap-3">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-pink-700/10 border border-pink-700/20 flex items-center justify-center">
            <Mail size={15} className="text-pink-700" />
          </div>
          <h2 className="section-title">Your Application Email</h2>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="btn-secondary"
            title="Copy to clipboard"
          >
            {copied ? (
              <><CheckCheck size={14} className="text-green-600" /><span className="text-green-600">Copied!</span></>
            ) : (
              <><Copy size={14} />Copy</>
            )}
          </button>
          <button
            onClick={handleDownload}
            className="btn-secondary"
            title="Download as .txt"
          >
            <Download size={14} />
            <span>Download</span>
          </button>
        </div>
      </div>

      {/* Email text */}
      <div className="bg-pink-100/60 rounded-xl border border-pink-400/20 p-5">
        <pre className="whitespace-pre-wrap text-sm text-pink-950 leading-relaxed font-sans">
          {email}
        </pre>
      </div>

      {/* Footer meta */}
      <div className="mt-4 flex items-center justify-between flex-wrap gap-3">
        {providerUsed && (
          <p className="text-xs text-pink-400">
            Generated by <span className="font-semibold text-pink-700">{providerUsed}</span>
          </p>
        )}

        {/* Matched project links */}
        {portfolioLinks?.length > 0 && (
          <div className="flex flex-col gap-1.5 w-full mt-2">
            <p className="text-xs font-semibold text-pink-700 uppercase tracking-wider">Matched Projects</p>
            <div className="flex flex-wrap gap-2">
              {portfolioLinks.map((link, i) => (
                <a
                  key={i}
                  href={link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 text-xs text-pink-700 hover:text-pink-950
                             border border-pink-400/30 rounded-full px-3 py-1
                             hover:border-pink-700 transition-colors"
                >
                  <Github size={10} />
                  Project {i + 1}
                </a>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
